### ISSUE TITLE
 Please help me fix this error !

### ISSUE THREAD

**Issue by tuanpk123** [samyarj/JCAPG-JURIX2023#1]
Hello ! I was running the code on your jupyter notebook and got the error as shown in the image: Even though I provided the correct API key and was pretty sure I had access to it. Please can you help me fix this error? Thank you very much !
![image](https://github.com/samyarj/JCAPG-JURIX2023/assets/165397125/2f43b0b3-db85-4522-9f53-47795fa8ca05)

**Comment by samyarj** [comment]
You don't seem to have access to the gpt-4 api. I believe that you need to make a payment of min. 5$ to get access: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4
